### ISSUE TITLE
Calling ddg.run on functions

### ISSUE THREAD

**Issue by margoseltzer** [End-to-end-provenance/RDataTracker-vagrant#8]
It's possible that I am such a naive R user that this is a really stupid thing to want to do, but here is something I ran into and I wondered if others thought this would be a useful feature.

I was debugging some scripts and really wanted to create a DDG for a particular function invocation (i.e., I'm typing into the console something like foo(A, B, C)).  It seems like right now, the assumption is that you generate DDGs from scripts (and I could certainly create a script that did nothing more than invoke my function, but that doesn't seem particularly efficient).

So, I wondered - is this just something a "real" R user would never do or might this be something useful?

Apologies -- put this in the wrong repo -- will fix.

**Comment by tfjmp** [comment]
Issue was moved to RDataTracker repository. Closing here.
